const images = [
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/gallery/exterior-3.jpg",
	"media/gallery/interior-1.jpg",
	"media/gallery/interior-2.jpg",
	"media/gallery/interior-3.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/gallery/wedding-1.jpg",
	"media/gallery/wedding-2.jpg",
	"media/gallery/wedding-3.jpg",
	"media/gallery/villas-1.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/gallery/villas-2.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/gallery/Ananta 3.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
	"media/public/main_pool_dawn__2_.jpg",
]
